### ISSUE TITLE
Firefox offers to save OpenVPN / IKEv2 username & password

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#100]
**Summary**
Firefox offers to save openVPN credentials when visiting account page. The user can choose to ignore this, but it is an unexpected behavior.

**Steps to reproduce**
1. Go to /dashboard#plans
2. Login
3. Click account

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/64122266-6043de00-cda1-11e9-9170-d0f981a56b4f.png)

**Comment by EpokK** [comment]
> As described in detail below, many modern browsers ignore the off value on certain fields in certain cases intentionally in order to give the user more control over autofilling fields. 
> Partial support refers to ignoring the off value for password fields. see related blog post
> Partial support in Chrome refers to the browser intentionally ignoring autocomplete="off" when the user uses the browser's autofill functionality. see bug
> Partial support in Firefox refers to ignoring autocomplete="off" for login forms. see bug
> Browser does not display previously submitted values as options with on value.
> Safari ignores the off value for username, email and password fields

Sources:
- https://caniuse.com/#search=autocomplete
- https://blogs.msdn.microsoft.com/ieinternals/2009/09/10/why-wont-ie-remember-my-login-info/
