### ISSUE TITLE
[Firefox] When report bug is opened for the first time, What happened? is marked as invalid

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#108]
**Steps to reproduce**
1. Go to login page
2. Open bug report modal
3. Notice how the `what happened?` input is marked in red.

**Video**
https://recordit.co/CS2qjG4Pht 

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/64165022-7ce52200-ce44-11e9-98b3-f75b940a75c8.png)

**Comment by nico3333fr** [comment]
Fixed via https://github.com/ProtonMail/design-system/commit/c4e744aacc345c6a5b4fc3b40b86a8c43ab3d05f
