### ISSUE TITLE
User with Plus plan cannot update plan to Visionary from Subscription  

### ISSUE THREAD

**Issue by gandriux** [ProtonMail/proton-vpn-settings#109]
1. Login with plus plan user
2. Navigate to Subscription https://vpnsettings.protonmail.blue/dashboard#subscription
3. Next to ProtonVPN plan press Update

Issue: In opened module user can select only downgrade to Basic plan or select the same plan (Plus)
<img width="940" alt="2019-09-03_13-17-40" src="https://user-images.githubusercontent.com/33432009/64165195-3e079a00-ce4d-11e9-8199-60d20f839087.png">

**Comment by EpokK** [comment]
People need to use the plan table for that.
