### ISSUE TITLE
[Edge, Safari] Missing arrow on dropdown element

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#117]
**Summary**
A typical dropdown element will have an arrow, indicating that more than one option is possible. That arrow is missing from our dropdown component.

**Current edge**
![image](https://user-images.githubusercontent.com/11393457/64184352-a2d1ed00-ce6b-11e9-9bd4-de711bacf346.png)

**Current safari**
![image](https://user-images.githubusercontent.com/11393457/64322855-a11b3d00-cfc3-11e9-9178-d0f020768b8c.png)

**Expected**
![image](https://user-images.githubusercontent.com/11393457/64184397-b1200900-ce6b-11e9-9bf0-c6cbc2b7fd06.png)

**Comment by RandomAdversary** [comment]
Update: The same issue can be found in safari.

**Comment by nico3333fr** [comment]
It seems to come from base64 inlining, as the input with "classic image" works on the Design system website. ping @mmso
