### ISSUE TITLE
Change password(for openvpn) , changes the username input field

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#118]
**Steps to reproduce**
1. Go to /account#openvpn
2. Change the username input field
3. Change the password input field
4. Click change password

**Current behavior**
The username input field is reverted to the username from step 1.

**Video**
https://recordit.co/2pAEpzkdnx

**Comment by EpokK** [comment]
We can popup a modal to edit `username` and `password` instead of displaying an input.

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/commit/ec639af10af449fe434974b46fd7888d5c299fe2
