### ISSUE TITLE
Fill progress bar

### ISSUE THREAD

**Issue by gandriux** [ProtonMail/proton-vpn-settings#124]
In the subscription section, progress bars are not filled: https://vpnsettings.protonmail.blue/dashboard#plans

<img width="960" alt="2019-09-04_10-14-03" src="https://user-images.githubusercontent.com/33432009/64241628-c7ca6c80-cf0c-11e9-9b44-f3028a4dac1c.png">

**Comment by nico3333fr** [comment]
This bug happens only on Chrome. It is caused by the `-webkit-appearance: none` added by autoprefixer.

I though it was ok with https://github.com/ProtonMail/design-system/blob/master/_sass/pm-styles/_pm-meterbar.scss#L13 but it seems this bug happens again.
