### ISSUE TITLE
Delete account section mentions deleting emails on vpn only accounts

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#131]
**Steps to reproduce**
1. Login with vpn only account
2. Go to /account
3. Scroll do delete account section

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/64253280-3adbdf00-cf1d-11e9-9ab3-a5b56bfbdad2.png)

**Expected behavior**
For vpn only accounts I expected to see the text from the current live website.
![image](https://user-images.githubusercontent.com/11393457/64253520-c3f31600-cf1d-11e9-9730-fe3f310b7f81.png)

**Comment by jovanjovanovski** [comment]
If the PM account has not been activated we should not mention messages linked with it. The notice should be:

```Deleting your account will permanently delete all data associated with it and it cannot be recovered. You will no longer be able to use the same username should you decide to create a new account```
