### ISSUE TITLE
The thank you modal has white background

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#135]
**Steps to reproduce**
1. Login
2. Upgrade your subscription 

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/64329164-14767c00-cfcf-11e9-85d5-a913e01803d5.png)

**Comment by EpokK** [comment]
@nico3333fr something probably change in modal structure? You can find the style applied on this modal in `SubscriptionModal.scss` from `react-components`.

**Comment by nico3333fr** [comment]
@EpokK I did not change anything, here is the modal I had a few minutes ago: 
![image](https://user-images.githubusercontent.com/2578321/64431051-e91c8b80-d0b9-11e9-9d21-015e07db9d75.png)

**Comment by RandomAdversary** [comment]
I got the same result again and, it looks like some css is getting blocked.
Might be an issue that happens only on blue, but I'm not 100% sure.

Here's the screenshot from the dev console:
![image](https://user-images.githubusercontent.com/11393457/64431789-5f6dbd80-d0bb-11e9-986f-efdb941aaf58.png)

**Comment by nico3333fr** [comment]
Good catch, these styles are missing on live, and they are present on local dev enviro:
```
.pm-modal.thanks-modal-container {
    background-color: #3c414e;
    color: #fff;
}
```
This is weird, I can't find them on Design system or on the project.
