### ISSUE TITLE
Text for _Security code_  is cut 

### ISSUE THREAD

**Issue by gandriux** [ProtonMail/proton-vpn-settings#140]
https://vpnsettings.protonmail.blue/payments#payment-methods

Steps:
1. In Payments section > Add card
2. In the opened pop-up, text for _Security code_  is cut 

<img width="236" alt="2019-09-05_15-37-33" src="https://user-images.githubusercontent.com/33432009/64342468-3aae1300-cff3-11e9-8f3b-c360aace7455.png">

**Comment by EpokK** [comment]
@matstaz Can we replace it by "CVC"?
