### ISSUE TITLE
Year in dropdown is cut in Payment details modal 

### ISSUE THREAD

**Issue by gandriux** [ProtonMail/proton-vpn-settings#141]
Precondition: User has already existing paid subscription plan

Steps:
1. Press to update in the subscription section
2. In Payment modal press Next until the last step
3. From payment method dropdown select Pay with credit/debit card 

<img width="353" alt="2019-09-06_10-08-42" src="https://user-images.githubusercontent.com/33432009/64410166-16097800-d093-11e9-8ace-c8d6df81931f.png">

**Comment by EpokK** [comment]
Change proposed:
<img width="498" alt="Capture d’écran 2019-09-06 à 10 37 55" src="https://user-images.githubusercontent.com/1345786/64413771-692efb00-d092-11e9-9e95-0e6a8ee5360d.png">
