### ISSUE TITLE
Top part of pages is not visible on responsive

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/proton-vpn-settings#144]
Tested on real Android devices. Browsers on which it happens:
* Chrome
* Brave

![menu](https://user-images.githubusercontent.com/54268246/64414640-5e796380-d09c-11e9-97b7-8070b9142d5f.gif)

**Comment by nico3333fr** [comment]
How did you get this? (device, reso, etc.) 

I've tested on my Android Nokia 6.1, I didn't have this issue.

**Comment by gytiskin** [comment]
I tried it on 2 devices: Pixel 2 (1920 x 1080) and OnePlus 7 Pro (3120 x 1440). Both run on Android 9.

**Comment by nico3333fr** [comment]
@gytiskin We sent a fix on vpnsettings.protonmail.blue , and I don't manage to reproduce anymore (I was able to before)

Could you refrech and check if the bug is still present?

**Comment by nico3333fr** [comment]
Ok, I'm still able to reproduce. 

It seems the bug happens only when you log in as a free member, and the plans are opened automatically. Possible te remove the automatic "scroll to" feature? @mmso
