### ISSUE TITLE
Entering less than minimum credit amount you can still proceed to verification

### ISSUE THREAD

**Issue by gandriux** [ProtonMail/proton-vpn-settings#145]
https://vpnsettings.protonmail.blue/dashboard#billing
Precondition: Add a credit card for default payment method

Steps:
1. Go to Dashboard
2. In billing details press _Add credits_
3. In the amount field enter less than 5 

Actual result: Top up button is still activated and redirects to verification
Expected result: Top up button should not be activated when the amount entered is less than 5
[Minimum.zip](https://github.com/ProtonMail/proton-vpn-settings/files/3583267/Minimum.zip)

**Comment by EpokK** [comment]
<img width="875" alt="Capture d’écran 2019-09-06 à 13 09 46" src="https://user-images.githubusercontent.com/1345786/64423868-caad9480-d0a7-11e9-931c-f1fb5452c37e.png">
I'm not able to reproduce this issue.

**Comment by gandriux** [comment]
Please try this scenario when the default payment method is set.
