### ISSUE TITLE
Plan upgrade modal opens and closes immediatelly on mobile

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/proton-vpn-settings#150]
Tested on Chrome and Firefox on Android.

![plan_upgrade_modal](https://user-images.githubusercontent.com/54268246/64424728-7eb41d00-d0b2-11e9-8907-c84bd7e4f8da.gif)

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/commit/2adaa489b30cd544200b1963a55d6c1740f44f8b
