### ISSUE TITLE
Signup page on responsive is a mess, can't click on some buttons

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/proton-vpn-settings#151]
Whole page is a mess. Also, cannot click on buttons that are under 'Sign up' header (Homepage and Back).

![ezgif com-resize](https://user-images.githubusercontent.com/54268246/64425900-d56f2600-d0b5-11e9-9bfc-c0d9893ac968.gif)

**Comment by EpokK** [comment]
That's why I said to focus on business logic for now. Responsive is not yet done.
