### ISSUE TITLE
CC card declined 

### ISSUE THREAD

**Issue by Yobama** [ProtonMail/proton-vpn-settings#155]
Trying to purchase paid plan - CC got declined. Error in console: 
Unhandled promise rejection StatusCodeError: “Unprocessable Entity”
   s helpers.js:12
   d helpers.js:83
   q es.promise.js:107
   r microtask.js:26
host-report-errors.js:6:56
Using blue API.
CC details: 
last digits:  0737
Exp: 08/22
Name: Proton Technologies

**Comment by EpokK** [comment]
API issue.

Also make effort to write **structured**,  **detailed** and **readable** issue please, use [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).
