### ISSUE TITLE
Upgrade to Basic, then Plus possible in one scenario

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-vpn-settings#157]
1. Select Free account
2. Enter username, password, email and submit form
3. Upgrade to Basic plan

Observed behavior: user can upgrade further towards Plus plan.
Expected behavior: user should not be able to upgrade a second time to Plus plan.

**Comment by vincaslt** [comment]
Just to clarify for anyone who will be re-testing this - it's talking about the upsell on the right side.
