### ISSUE TITLE
Edit credit card modal creates new card

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#159]
**Steps to reproduce**
1. Go to /payments
2. Click edit on the card
3. Change the name and credit card number
4. Click save

**Expected**
Current card to be updated.

**Current behavior**
New card is added.

**Video**
https://recordit.co/o4SS5L0rMU

**Comment by EpokK** [comment]
If you change the card number, you are not updating it. You are creating a new one.

**Comment by mmso** [comment]
@EpokK what do you think about disabling the credit card number input when you are in edit mode?
