### ISSUE TITLE
Add text on top of plans in the dashboard

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-vpn-settings#164]
to make the table less boring, please add the text on top of it as shown here: https://app.zeplin.io/project/5bb1deae290afc111d140a3f/screen/5bf80bbd9befb87e830a87a1

if user has only paid ProtonMail, we keep the first line of text
if user has only Paid ProtonVPN, we keep the first line of text
if the user has both paid ProtonMail and ProtonVPN, then the first line can be removed

**Comment by EpokK** [comment]
I did it on mail side.
