### ISSUE TITLE
Missing the upsell text when one plan is FREE

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-vpn-settings#165]
We do not see the text "Combine paid ProtonMail and ProtonVPN and get a 20% discount on both" in the subscription section when one plan is FREE and the other plan is PAID
![Capture d’écran 2019-09-06 à 17 24 14](https://user-images.githubusercontent.com/40168570/64439940-51279d80-d0cb-11e9-8ccc-4cf4a67a9ce5.png)

**Comment by EpokK** [comment]
This behavior is correct. We display the message only if the user already has a part of the bundle (`plus` or `vpnplus`) or  no subscription.
