### ISSUE TITLE
When billing cycle differ in Select a plan and full plan comparison, Cannot read property error 

### ISSUE THREAD

**Issue by gandriux** [ProtonMail/proton-vpn-settings#168]
https://vpnsettings.protonmail.blue/signup
Step:

1. Press _View full plan comparison_
2. Select different billing cycle compared to the dashboard(e.g. Annual)
3. Press _Get ***_ plan button 

Note: in case defect not reproducible according to above steps, continue with step 4

4. Change the billing cycle in the dashboard (different from what was selected in View full plan comparison) - e.g. Monthly
5. Press  _Get ***_ plan button 

Issue: _TypeError: Cannot read property 'price' of undefined_
<img width="960" alt="2019-09-09_9-41-14" src="https://user-images.githubusercontent.com/33432009/64508824-05e9d680-d2e7-11e9-8610-cf92c8b560c5.png">

[ConnotReadProperty.zip](https://github.com/ProtonMail/proton-vpn-settings/files/3589012/ConnotReadProperty.zip)

**Comment by vincaslt** [comment]
The actual bug had nothing to do with "view comparison", it was just a coincidence it was discovered like that. The actual bug was occuring when "Monthly" cycle was selected and any of the paid plans was chosen.
