### ISSUE TITLE
Download configurations using xhr

### ISSUE THREAD

**Issue by kaplun** [ProtonMail/proton-vpn-settings#179]
Currently when user downloads VPN configurations they basically follow an HTML link and download them directly using: https://docs.protontech.ch/#vpn-get-vpn-server-config-get

We should rather use `xhr` so that we can pass proper authorization/authentication headers and we can thus restrict server-side the type of configuration the user can download.

**Comment by vincaslt** [comment]
In React app frontend makes an XHR request with the UID headers for logged in users. BE should prevent unauthenticated access to the endpoint. The old app used to generate a link.
