### ISSUE TITLE
Add advice to check spam folder after requesting verification code

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-vpn-settings#181]
On the verification screen, after hitting "send", update the text to say:

Enter the verification code that was sent to [email address]. If you don't find the email in your inbox, please check your spam folder.

**Comment by Yobama** [comment]
Text "Check spam folder" is not displayed; email address is missing. FF on Mac.
![image](https://user-images.githubusercontent.com/54276521/64595658-b53faf80-d3b2-11e9-805b-bc16ddc4cb35.png)
