### ISSUE TITLE
Check how we handle FE validation of text input

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-vpn-settings#182]
We should have a consistent way of handling text input validation.

If user puts focus in the text input, the placeholder text disappears

If user focuses out of the text input WITHOUT typing a string of text, we should highlight the text input and show an inline error message "This field is required" and the placeholder text appears again

if user focuses out of the text input and the input DOES NOT MATCH front end validation, we should highlight the text input and show an inline error messages "The email is not in the right format" or whatever is suitable for the input.

**Comment by nico3333fr** [comment]
Fixed via https://github.com/ProtonMail/design-system/commit/8f173a7978bf01fa47492276872d122a0659f2ad
