### ISSUE TITLE
Bugs in human confirmation

### ISSUE THREAD

**Issue by nico3333fr** [ProtonMail/proton-vpn-settings#187]
EXPECTED ~1) I tried to confirm I'm human using an email, so I put an address inside the field, I receive the confirmation number, fill in into the field:~

~Could it be possible to know that the email is already used BEFORE receiving the link?~

2) Once this done, I clicked on "did not receive the code", and the modal seems bugged:
![image](https://user-images.githubusercontent.com/2578321/64542052-2768b380-d323-11e9-9782-fc9e7d05c1f2.png)
"Click below to resend the code to <missing email>. If"

**Comment by nico3333fr** [comment]
When I retry, it seem the sentence is not complete:
![image](https://user-images.githubusercontent.com/2578321/64542226-7a426b00-d323-11e9-84fb-93a421e5f0ea.png)

Enter the verification code that was sent to <you/your email/?>

**Comment by EpokK** [comment]
Should be fixed.
