### ISSUE TITLE
Add "already have an account?" question that leads user to log in screen

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-vpn-settings#189]
On the following pages, add an "already have an account" section. If user clicks on login, he would be taken to the login page and we should remember the plan selected so that upon logging in, we can take him through the subscription flow (ideally).

Pages where we should add it:
- create account page
- verification page
- payment page

Here are 2 options worth considering (full width or in line with left hand content). I kind of prefer the left hand alignement.
![Sign up - Regular traffic - Free - Account creation - v2](https://user-images.githubusercontent.com/40168570/64548535-16be3a80-d32f-11e9-884e-108e595c3843.png)
![Sign up - Regular traffic - Free - Account creation](https://user-images.githubusercontent.com/40168570/64548536-16be3a80-d32f-11e9-8369-101bfae56654.png)

**Comment by EpokK** [comment]
@nico3333fr The error zone should not appear if the user didn't loose the focus on the input field.
