### ISSUE TITLE
After logout user is shown an empty dashboard page

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/proton-vpn-settings#193]
Scenario:

* Login (make sure user is on Dashboard page)
* Click on top right menu and Logout
  * Empty Dashboard page is displayed

**Comment by mmso** [comment]
Can you expand the steps to reproduce please? I can't

**Comment by gytiskin** [comment]
Try this one:

* Open fresh Incognito window
* Login
* Scroll down to the bottom of the Dashboard page
* Logout

**Comment by mmso** [comment]
Still nothing. Can you make a video please?

**Comment by gytiskin** [comment]
https://recordit.co/NOkfK1cCyi

It's possibly related to me going to /dashboard page initially, then log in and log out.

**Comment by mmso** [comment]
Can you open the developer tools to see if there is an error please?

**Comment by RandomAdversary** [comment]
I can reproduce is too. The dev tools console is empty.

**Comment by mmso** [comment]
Thanks @RandomAdversary. @gytiskin explained it again and now I was able to reproduce.
