### ISSUE TITLE
[Suggestion] Use different vertical positioning for the username on vpn only accounts

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#201]
**Summary**
The vpn only accounts don't have an email address. Because of this, the positioning of the username looks a bit weird. 

**Screenshots**
**Vpn only**
![image](https://user-images.githubusercontent.com/11393457/64609155-8cc4af00-d3cc-11e9-8af8-ce856007c0cc.png)

**vpn + mail**
![image](https://user-images.githubusercontent.com/11393457/64609194-ab2aaa80-d3cc-11e9-8d86-0398350501c5.png)

**Comment by nico3333fr** [comment]
Well, time to use magic `:empty selector` ;)
