### ISSUE TITLE
Cannot find module './xy.svg' error when showing error message

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#205]
**Summary**
See the attached video. Notice the error in the dev console.

**Video**
https://recordit.co/MY3vIDXobG

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/64625109-eee0dc80-d3eb-11e9-8ace-1d846d852c91.png)

**Comment by RandomAdversary** [comment]
I noticed additional server named xy(see https://github.com/ProtonMail/proton-vpn-settings/issues/206).
Could this be the cause of the error?

**Comment by mmso** [comment]
Yeah, but it shouldn't error out like that anyway so I'll make a fix for that
