### ISSUE TITLE
Deleting user with active paid plan throws error

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/proton-vpn-settings#209]
**Description:** Deleting account with active paid plan shows error, API returns error statuses, but user account is scheduled for deletion anyways.

**Scenario:**

* Sign up with user with paid plan (I tried with Basic)
* Navigate to 'Account', click 'Delete' your account
* Fill 'Feedback' and 'Login password' fields and click 'Delete'
  * Notification with 'Invalid input' error displayed
  * '/api/reports/bug' returns 400 Bad request
  * '/api/events/< token >' returns 401 Unauthorized
  * '/api/auth/refresh' returns 422 Unprocessable Entity

**Video:** https://recordit.co/qfmDq4Hyaz

**Comment by mmso** [comment]
Still an issue with the report request, looking into that
