### ISSUE TITLE
Selected plan is not show on plans comparison

### ISSUE THREAD

**Issue by Yobama** [ProtonMail/proton-vpn-settings#21]
![Screenshot 2019-08-19 at 16 25 19](https://user-images.githubusercontent.com/54276521/63273279-fbb35a00-c29d-11e9-9555-bdd14f913533.png)

**Comment by EpokK** [comment]
Changes done on `PlansTable` component, @nico3333fr will address the rest.

**Comment by mmso** [comment]
Done by @nico3333fr in https://github.com/ProtonMail/proton-vpn-settings/commit/416521fd67aef868186f59d0dd4e71fbc1c5a4dd
