### ISSUE TITLE
[Suggestion] Show payment method errors in the payments modal

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#216]
**Steps to reproduce**
1. Open donation modal
2. Select bitcoin

**Expected behavior**
Error message to be shown bellow the payment selection dropdown. 
The same way we do, when paypal is not available.

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/64694037-01fdb600-d499-11e9-9fad-60e454358e71.png)

**Comment by EpokK** [comment]
This has been fixed by https://github.com/ProtonMail/react-components/commit/a5fa3939987378afa838a72575e954b748ef05d3
