### ISSUE TITLE
Add deeplink to return to Android app after sign up

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/proton-vpn-settings#228]
If user comes to ../signup?from=mobile, after successful Sign up a redirect to 'protonvpn://registered' should happen. This is used in Android to return user back to the app.

**Comment by gytiskin** [comment]
Tested on production, not working anymore (after the fix tested on dev env., worked fine). Reopening.

**Comment by EpokK** [comment]
I tested, the Android app crashes. Not a FE bug.
