### ISSUE TITLE
VPN plans presented when upgrading ProtonMail via ProtonVPN Dashboard

### ISSUE THREAD

**Issue by NikolaDamevski** [ProtonMail/proton-vpn-settings#237]
When trying to upgrade ProtonMail via the new ProtonVPN Dashboard the screen that is presented is referring to ProtonVPN plans, not ProtonMail plans. Regardless of which option you choose, it takes you to ProtonMail Plus option. 

Steps to reproduce:
-At ProtonVPN Dashboard choose "Upgrade" for the ProtonMail plan
1. ProtonVPN plans are presented instead of ProtonMail plans
2. The selection is always ProtonMail Plus regardless of which option is chosen

Attached screenshots:
![image](https://user-images.githubusercontent.com/49149795/64851288-62b2fd00-d617-11e9-9275-6d5fd922a15f.png)

![image](https://user-images.githubusercontent.com/49149795/64851318-6e062880-d617-11e9-8211-b2a082e411d3.png)

![image](https://user-images.githubusercontent.com/49149795/64851329-73fc0980-d617-11e9-94c4-1733aef83b21.png)

**Comment by EpokK** [comment]
Yeah, expected.

**Comment by matstaz** [comment]
Yeah this is expected and will be improved with what we are working on with Andy. I understand this decision is a little bit confusing but it is also backed by our intention to drive more profit, hence why we always auto-select Plus.
