### ISSUE TITLE
On navigation to Payments, tables briefly appear before disappearing

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/proton-vpn-settings#242]
When navigating to Payments page, Payment Methods and Invoices tables briefly appear, but disappear when there's no data.

**Video:**
https://recordit.co/rj5CTZtIY8

**Comment by EpokK** [comment]
The loader appears when we load data. For you it flash because your connexion is probably good 😄 
![Capture d’écran 2019-09-13 à 15 07 36](https://user-images.githubusercontent.com/1345786/64864836-3f4c7a00-d638-11e9-8418-6eed75ecb9da.png)

**Comment by gytiskin** [comment]
I'd say a prettier approach here would be to display only the loader while loading (with no table column info), and only if there are records, display the table with data.
