### ISSUE TITLE
[Safari] Scroll stops immediately after releasing the finger while scrolling

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/proton-vpn-settings#244]
On Safari (iPhone, iPad), scrolling in all pages is difficult because releasing the finger while scrolling stops the scroll.

**Video:** 
![ezgif com-resize (1)](https://user-images.githubusercontent.com/54268246/64865744-abcc7680-d642-11e9-8831-2bd5ac5c3970.gif)

**Comment by nico3333fr** [comment]
Sh.. I forgot to use `scroll-smooth-touch` helper https://design-system-beta.netlify.com/helpers/
Will send a fix asap.
