### ISSUE TITLE
[Chrome] Issue after scrolling

### ISSUE THREAD

**Issue by antoinefq** [ProtonMail/proton-vpn-settings#246]
1. Go to `Dashboard`
2. You will scroll until you see subscription or billing details for example
3. Then you will go to another page like `Account`, `Downloads` 
4. You wont be at the top of the page (as it should be). 

In Firefox, it is working perfectly.

+

"Delete" page is not available (can be found in Account navigation).

**Comment by EpokK** [comment]
> "Delete" page is not available (can be found in Account navigation).

This part has been reported in https://github.com/ProtonMail/proton-vpn-settings/issues/88
