### ISSUE TITLE
Selecting the Free plan cancels the whole bundle

### ISSUE THREAD

**Issue by ZoranStojanovski** [ProtonMail/proton-vpn-settings#248]
The previous behavior was:

*User has a bundle of ProtonMail + ProtonVPN
- Select the Free plan in the ProtonVPN Dashboard
- The ProtonVPN plan is canceled
- The ProtonMail plan is renewed automatically due to the cancellation of the bundle

Now, if you have bundle plans and you select the Free plan in the ProtonVPN Dashboard, the whole bundle is actually canceled to free. 
This may be bad for revenue and not clear for users as there is no clarification that their ProtonMail plan will be also canceled in the process. 

If this is intended for some reason, we need to add a notification that the user's ProtonMail plan is canceled in the process.

**Comment by EpokK** [comment]
Old version:
<img width="542" alt="Capture d’écran 2019-09-15 à 15 36 10" src="https://user-images.githubusercontent.com/1345786/64922343-a13ee800-d7ce-11e9-93fb-86972e75a662.png">

```
This will downgrade your VPN to a free subscription. ProtonVPN is free software that is possible thanks to donations and paid accounts. Please consider making a donation so we can continue to enable secure internet anywhere for everyone.
```
