### ISSUE TITLE
A couple of issues with Email subscriptions checkboxes

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/proton-vpn-settings#251]
1. Clicking on one checkbox highlights all checkboxes.
2. Clicking at the very bottom of one checkbox actually records a click on the checkbox below it.

**Both cases can be seen in the video:** 
https://recordit.co/AA563QsdLx

**Comment by RandomAdversary** [comment]
The first issue is expected behavior. See: https://github.com/ProtonMail/react-components/issues/28 for more info
