### ISSUE TITLE
Something went wrong message after canceling the VPN plan while having a bundle

### ISSUE THREAD

**Issue by ZoranStojanovski** [ProtonMail/proton-vpn-settings#258]
Once the ProtonVPN plan is canceled in the Dashboard, the action is performed (the VPN plan is canceled and the PM plan is renewed), but there's a screen with an error message which can be seen in the video below:

Steps to reproduce:
1) Log-in to protonvpn.com with an account that has a bundle ProtonMail and ProtonVPN plan
2) Downgrade the ProtonVPN subscription in the Dashboard
3) The **Something went wrong** screen should pop-up right after downgrading

Video: https://recordit.co/aQNAjFzOcV

**Comment by RandomAdversary** [comment]
Screenshot from the error in dev console, when this happens:
![image](https://user-images.githubusercontent.com/11393457/65027365-8093a100-d93a-11e9-8c65-03456318b0e9.png)
