### ISSUE TITLE
When selected, password input size doesn't match password reveal button size

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#261]
**Steps to reproduce**
1. Go to login
2. Click on the password input

**Screenshots**
**Safari**
![image](https://user-images.githubusercontent.com/11393457/65123173-fb1ff780-d9f2-11e9-89f9-f11f04f3608d.png)

**Chrome**
![image](https://user-images.githubusercontent.com/11393457/65123065-c2801e00-d9f2-11e9-8cf6-62dbd0123e75.png)

**Comment by nico3333fr** [comment]
Yes, I had to "fake" the input (the "real" input is inside). 

Will have to manage outline on this case :)
