### ISSUE TITLE
Unable to download OpenVPN configuration files on an iOS 12 device and older

### ISSUE THREAD

**Issue by protonkeni** [ProtonMail/proton-vpn-settings#264]
When you try to download an OpenVPN configuration file the buttons are responsive but do not perform the expected action of downloading the desired file.

The issue appears to be related to the way the manual downloads are handled on the iOS version 12 and older since it appears that on iOS beta version 13 the issue does not occur.

Device model: iPhone 7
iOS version: 12.4.1
Browsers tested: Safari, Chrome, Brave

Video demonstrating the issue:
https://recordit.co/1TomoaqCei

**Comment by EpokK** [comment]
It's [coming](https://www.apple.com/ios/ios-13/features/).
```
Downloads folder
A new downloads folder gives you a central place to access your web downloads and attachments from Safari and Mail.
```

**Comment by kaplun** [comment]
But for iOS 13 is fine, right? Because at the same time we are rolling out this month or next one support for OpenVPN in ProtonVPN iOS, so there's going to be even less need for downloading th OpenVPN configurations.

**Comment by EpokK** [comment]
Fixed.
