### ISSUE TITLE
Missing PayPal payment option in "Add Credits" section at ProtonVPN Dashboard

### ISSUE THREAD

**Issue by NikolaDamevski** [ProtonMail/proton-vpn-settings#265]
The PayPal payment method is missing in the "Add Credits" section at ProtonVPN Dashboard.

Screenshots below:

![image](https://user-images.githubusercontent.com/49149795/65144513-cd997500-da17-11e9-869d-a589078f1b22.png)

![image](https://user-images.githubusercontent.com/49149795/65144615-ff124080-da17-11e9-9d51-39254271feea.png)

**Comment by EpokK** [comment]
This is expected, right now we allow new PayPal as payment method only for `isYearly || isTwoYear || isMonthlyValid || isInvoice`.
