### ISSUE TITLE
Not possible to change the BUNDLE coupon with another one while upgrading

### ISSUE THREAD

**Issue by ZoranStojanovski** [ProtonMail/proton-vpn-settings#266]
If the user has a ProtonMail plan and he upgrades the ProtonVPN plan, it is not possible to remove the BUNDLE coupon and add another one which our affiliate/marketing team has potentially provided.

The BUNDLE coupon should be pre-applied, but the coupon field should be editable similarly as it is on the ProtonMail side in this situation.

Screenshot:
![bundlecoupon](https://user-images.githubusercontent.com/26218807/65226889-f9743380-dac7-11e9-8b58-4c8e0c05b4ef.PNG)

**Comment by EpokK** [comment]
That's expected.
