### ISSUE TITLE
[Signup] Add a tooltip to explain basic privacy features

### ISSUE THREAD

**Issue by dhoko** [ProtonMail/proton-vpn-settings#274]
Open the signup https://account.protonvpn.com/signup

There is no tooltip to explain the diff between basic/advanced feature 
![Screenshot from 2019-09-24 09-38-12](https://user-images.githubusercontent.com/713283/65491342-29984980-deaf-11e9-9d12-d1dde2a2acf6.png)

What does it mean ?

**Comment by EpokK** [comment]
![Capture d’écran 2019-09-24 à 10 06 27](https://user-images.githubusercontent.com/1345786/65493409-14251e80-deb3-11e9-815a-92f731e05693.png)
![Capture d’écran 2019-09-24 à 10 07 02](https://user-images.githubusercontent.com/1345786/65493410-14251e80-deb3-11e9-880e-02ceddb7b353.png)
