### ISSUE TITLE
Missing try again button for failed payments

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#282]
**Steps to reproduce**
1. Add 3ds credit card
2. Fail the payment

**Current behavior**
![image](https://user-images.githubusercontent.com/11393457/65520108-58caad00-dee7-11e9-8c22-9515073c0e74.png)

**Expected**
![image](https://user-images.githubusercontent.com/11393457/65520130-64b66f00-dee7-11e9-9b39-a443e10d8b8a.png)

**Comment by EpokK** [comment]
Expected.
