### ISSUE TITLE
Card info is lost if I click cancel on payment verification modal

### ISSUE THREAD

**Issue by DeepSpaceHarbor** [ProtonMail/proton-vpn-settings#290]
**Steps to reproduce**
1. Login
2. Switch to another vpn plan
3. When asked for payment, use 3ds card.
4. When payment verification modal is shown, click cancel.

**Current behavior**
The credit card info from step 3 is lost.

**Video**
https://recordit.co/ptSGWd47jH

**Comment by RandomAdversary** [comment]
Update: Same issue can be reproduced if I fail the 3DS verification, and click `use different payment method`,

**Comment by EpokK** [comment]
It's expected, the browser should save the value for the user. Not the client.

**Comment by RandomAdversary** [comment]
@EpokK This has nothing to do with browser saving the data. 
The exact same issue was fixed for signup https://github.com/ProtonMail/proton-vpn-settings/issues/280 , I think we should fix it here as well.
