### ISSUE TITLE
Cancel downgrade shows error in browser console

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/proton-vpn-settings#62]
Scenario:

* Make sure user has paid plan
* Navigate to /dashboard#plans
* Click 'Update' next to FREE plan
* Click 'Cancel' in the 'Confirm downgrade' modal

**Result**: modal is closed, but browser console shows error 'Uncaught (in promise) undefined'

**Comment by mmso** [comment]
Merging this one with https://github.com/ProtonMail/proton-vpn-settings/issues/61 since they are about the same thing
