### ISSUE TITLE
In header, the support text is hidden on 1366x768 resolution

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#63]
**Summary**
On screens with 1366x768 resolution the support text is hidden. if you see at the screenshot, there's more than enough space for the text. We should show the full text.

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/63466941-a5444800-c464-11e9-860c-7b1422524c86.png)

**Comment by nico3333fr** [comment]
The code which was doing this was for Angular, I've removed it from Design system via https://github.com/ProtonMail/design-system/commit/5ce5b019de29566d31110772e6031575b9b12871
