### ISSUE TITLE
Missing option for Notifications/Recovery email change

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-vpn-settings#87]
**Summary**
In the current vpn web app the user can change the recovery email.

This option is missing in the latest(v4) version.

![image](https://user-images.githubusercontent.com/11393457/63954472-6ffeb200-ca83-11e9-9fd7-61b2845c6190.png)

**Comment by matstaz** [comment]
that should be available in the Account tab, right? since we leverage the same as Mail account (if I understand what you do @EpokK correctly trying to stick to the same content as much as possible
