### ISSUE TITLE
Drop old browsers

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/proton-vpn-settings#89]
For ProtonVPN Settings release, we need to drop at least IE11. Check with @jovanjovanovski for the text and behavior expected please.

**Comment by mmso** [comment]
Done in https://github.com/ProtonMail/proton-pack/commit/f8adfddc7b9efec087b0f3807fc5e5ef91e84748 and https://github.com/ProtonMail/proton-shared/commit/cdf1f0c8eafe3886e91b4469350ecc739ff62837
