### ISSUE TITLE
Free users cannot download the Servers configs of free servers as zip file

### ISSUE THREAD

**Issue by stefchoz** [ProtonMail/proton-vpn-settings#91]
Free users cannot use the "**Download All Configurations**" option in order to download the **Server configs** which are available for Free plan. It works fine on the current version.

Steps to reproduce:

- Login with a Free account
- Navigate to **Downloads**
- select **Server Configs** 
- Scroll down to the bottom of the page
- "**Download All Configurations**" is greyed out

Expected behavior: Free users should be able to download the Server configs (as ZIP file) of the Free servers only:

- If UDP protocol is selected:

```
nl-free-01.protonvpn.com.udp.ovpn
nl-free-02.protonvpn.com.udp.ovpn
us-free-01.protonvpn.com.udp.ovpn
us-free-02.protonvpn.com.udp.ovpn
jp-free-01.protonvpn.com.udp.ovpn
jp-free-02.protonvpn.com.udp.ovpn
jp-free-03.protonvpn.com.udp.ovpn
```

- If TCP protocol is selected:

```
nl-free-01.protonvpn.com.tcp.ovpn
nl-free-02.protonvpn.com.tcp.ovpn
us-free-01.protonvpn.com.tcp.ovpn
us-free-02.protonvpn.com.tcp.ovpn
jp-free-01.protonvpn.com.tcp.ovpn
jp-free-02.protonvpn.com.tcp.ovpn
jp-free-03.protonvpn.com.tcp.ovpn
```

**Comment by EpokK** [comment]
It's an API issue, the FE doesn’t have control to restrict config file to this list. But we will re-enable the button.
