### ISSUE TITLE
Active Configs buttons look like they are disabled

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/proton-vpn-settings#93]
<img width="849" alt="Screenshot 2019-09-02 at 09 46 18" src="https://user-images.githubusercontent.com/54268246/64103421-e567cc80-cd7a-11e9-86d0-3771e406e96b.png">

**Comment by nico3333fr** [comment]
Here are active states for reference 
![image](https://user-images.githubusercontent.com/2578321/64105505-ab94c700-cd76-11e9-9f14-d44ed1394016.png)
